/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GolfCartCartNumberRouteImport } from './routes/golf-cart.$cartNumber'
import { Route as GolfCartCompletedFirstNameRouteImport } from './routes/golf-cart-completed.$firstName'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GolfCartCartNumberRoute = GolfCartCartNumberRouteImport.update({
  id: '/golf-cart/$cartNumber',
  path: '/golf-cart/$cartNumber',
  getParentRoute: () => rootRouteImport,
} as any)
const GolfCartCompletedFirstNameRoute =
  GolfCartCompletedFirstNameRouteImport.update({
    id: '/golf-cart-completed/$firstName',
    path: '/golf-cart-completed/$firstName',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/golf-cart-completed/$firstName': typeof GolfCartCompletedFirstNameRoute
  '/golf-cart/$cartNumber': typeof GolfCartCartNumberRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/golf-cart-completed/$firstName': typeof GolfCartCompletedFirstNameRoute
  '/golf-cart/$cartNumber': typeof GolfCartCartNumberRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/golf-cart-completed/$firstName': typeof GolfCartCompletedFirstNameRoute
  '/golf-cart/$cartNumber': typeof GolfCartCartNumberRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/golf-cart-completed/$firstName' | '/golf-cart/$cartNumber'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/golf-cart-completed/$firstName' | '/golf-cart/$cartNumber'
  id:
    | '__root__'
    | '/'
    | '/golf-cart-completed/$firstName'
    | '/golf-cart/$cartNumber'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GolfCartCompletedFirstNameRoute: typeof GolfCartCompletedFirstNameRoute
  GolfCartCartNumberRoute: typeof GolfCartCartNumberRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/golf-cart/$cartNumber': {
      id: '/golf-cart/$cartNumber'
      path: '/golf-cart/$cartNumber'
      fullPath: '/golf-cart/$cartNumber'
      preLoaderRoute: typeof GolfCartCartNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/golf-cart-completed/$firstName': {
      id: '/golf-cart-completed/$firstName'
      path: '/golf-cart-completed/$firstName'
      fullPath: '/golf-cart-completed/$firstName'
      preLoaderRoute: typeof GolfCartCompletedFirstNameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GolfCartCompletedFirstNameRoute: GolfCartCompletedFirstNameRoute,
  GolfCartCartNumberRoute: GolfCartCartNumberRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
